### ISSUE TITLE
Task's parent elements aren't considered

### ISSUE THREAD

**Issue by blackwind** [GuardRex/vscode-status-bar-tasks#8] opened 2016-08-25 02:22 UTC
Given the following example `tasks.json`:

```
{
  "version": "0.1.0",
  "command": "deploy",
  "args": ["my-project"],
  "isShellCommand": true,
  "suppressTaskName": true,
  "tasks": [
    {
      "taskName": "Build",
      "args": ["-b"],
      "isBuildCommand": true
    }
  ]
}
```

When Ctrl+Shift+B is pressed, VSC combines `command` and both `args` lists to make "deploy my-project -b" and correctly runs my build task. When I click "Build" on the statusbar, SBT returns:

```
'-b' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by guardrex** [comment] 2016-08-25 15:46
That's because the full command must appear as the arguments in the tasks command. This would be for Windows (I'll come back to Mac in a sec) ...

``` json
{
  "version": "0.1.0",
  "command": "cmd",
  "args": "/c",
  "isShellCommand": true,
  "suppressTaskName": true,
  "tasks": [
    {
      "taskName": "Build",
      "args": ["deploy", "my-project", "-b"],
      "isBuildCommand": true
    }
  ]
}
```

It's documented on the [ReadMe](https://marketplace.visualstudio.com/items?itemName=GuardRex.status-bar-tasks), but not everyone sees it because many install the extension from VSC and the ReadMe isn't shown if the extension is installed directly from VSC.

The reason behind this is that VSC does something that many folks think is pretty dumb (there is an open issue on it with lots of complaints and they say they will address it at some point): It forces you to only have one main command up there that gets stuck on to every task you have. This works **horribly** in practice IMO, because devs (me!) usually have a variety of different commands that they want to run. Some of my tasks are for `dotnet` commands, like `dotnet publish`, while I have other commands for things like Gulp ... `gulp bundle_some_files_gulp_task`. Having a common prefix breaks the ease of just having completely individual tasks that don't run on a common command.

Therefore, I built it so that what you put in the `args` of the task is the full command. The top-level command then just becomes the shell itself and is only used if you trigger the VSC task via the Command Palette or keyboard shortcut. For Windows, it's just `cmd /c`, which would be triggered as a prefix to all tasks when you use the Command Palette (e.g., `F1 > Tasks: Run Tasks > task Build` in this case). My extension ignores it totally. My extension uses Node's `child_process` module to execute the task arguments directly ... the arguments and nothing else.

For Mac .... great question ... I think, but I'm not sure about this ... that your shell would be one of three possibilities for that top-level `command`: (1) empty string, (2) `bash`, or (3) `open`. I'm not sure which one will work, but this would be a good time to find out, and I'll add it to the docs for the next revision. Try just using `open` and see if that works ...

``` json
{
  "version": "0.1.0",
  "command": "open",
  "isShellCommand": true,
  "suppressTaskName": true,
  "tasks": [
    {
      "taskName": "Build",
      "args": ["deploy", "my-project", "-b"],
      "isBuildCommand": true
    }
  ]
}
```

... and keep in mind that when I say "that works" I mean as you suggested in your OP ... via the keyboard shortcut and/or the Command Palette. I know for a fact that clicking the status bar task will work, because you can see the correct full command in the arguments for `deploy my-project -b`, which is the only thing that the extension will execute. My extension is going to ignore the `open` up there.

[EDIT] The reason I think it will be `open` is found here: http://stackoverflow.com/questions/1308755/launch-an-app-on-os-x-with-command-line

**Comment by blackwind** [comment] 2016-08-25 20:56
See, this isn't an unreasonable explanation or anything, but the reality is, whether it might be changing in the future or not, this is how VSC handles it today, so this is what many people are going to be using, so it should work in your extension today. And hey, if someone happens to already be using the method you suggest, "cmd /c deploy my-project -b" would work just as well executed from Node.

**Comment by guardrex** [comment] 2016-08-25 22:23
> "cmd /c deploy my-project -b" would work just as well executed from Node.

The problem is that `cmd /c` would be stuck on every command run (as you say ... the way VSC is supposed to work :smile: ), and I didn't want to gamble that it would be ok in all cases to open a shell to run the command. Maybe that's a bad guess on my part ... it definitely led to an "opinionated" extension: (1) The dev probably won't use the Command Palette opting to always click their status bar task, (2) The dev probably wants to state explicitly in the arguments exactly what they want run ... nothing more ... nothing less. I assumed that if they wanted `cmd /c`, then they could stick that on the arguments. Maybe that's all bad thinking on my part.

I was hoping that they would have this fixed by now ... see https://github.com/Microsoft/vscode/issues/981 and https://github.com/Microsoft/vscode/issues/6496. If they fix it, then we'd all be golden. I'm going to ask them about taking it off the backlog.

For Mac and Linux ... Mac in this case, that's why I was asking if you put `open` or even just leave the top-level command blank, does it run ok? ... I mean from the Command Palette?

> this is how VSC handles it today, so this is what many people are going to be using

Yep! Something needs to be done ... either on my side or their side. If they tell me that the feature request has gone in to a black hole or if they just don't respond, then I would like to have a custom setting in VS Code, where you can instruct the extension how you want it to behave: "Use Top-Level Command When Running Tasks" ... True/False. That would make everyone happy. Let's see what they say first.

**Comment by blackwind** [comment] 2016-08-25 22:40
> I assumed that if they wanted cmd /c, then they could stick that on the arguments. Maybe that's all bad thinking on my part.

As I say, not an unreasonable assumption, but the fact remains, if it works through the command palette, it should work through the extension as well.

> For Mac and Linux ... Mac in this case, that's why I was asking if you put open or even just leave the top-level command blank, does it run ok? ... I mean from the Command Palette?

Windows developer here, so I'm afraid I can't speak to this.

> If they tell me that the feature request has gone in to a black hole or if they just don't respond, then I would like to have a custom setting in VS Code, where you can instruct the extension how you want it to behave: "Use Top-Level Command When Running Tasks" ... True/False.

I recommend defaulting that to `true` so there's no out-of-the-box friction. This is the kind of thing that leads to uninstalls and bad reviews.

> Let's see what they say first.

Sounds good. :)

**Comment by guardrex** [comment] 2016-08-26 15:09
Hum ... https://github.com/Microsoft/vscode/issues/981#issuecomment-242699427

Well, we have our answer: They would like to address it but they have no idea when they'll get around to it. Sorry to see the "Since we are a small team of developers" remark, which I've seen from the OData folks and hinted by the Azure Identity and Storage, and the .NET devs, too ... MS made something like **$20 BILLION** dollars last year. Shareholders are more important than fixing major service and app issues I guess.

The problem with the call for a possible PR for them is that no doubt whatever solution is settled upon will be as opinionated as what I've done with the extension. I like the pitch of https://github.com/Microsoft/vscode/issues/6496 ... an override. I'm still not inclined to force devs to accept the top-level command if they don't want it on a by-task basis. I'll have to go with a custom bool setting to override the default behavior globally.

I have one major project that I must finish before I can get to this, so it will take at least two weeks. Thanks for raising the issue and discussing it with me.

**Comment by blackwind** [comment] 2016-10-21 04:34
Since #11 won't be happening any time soon (no further work has been done on [the issues I referenced](https://github.com/GuardRex/vscode-status-bar-tasks/issues/11#issuecomment-245130118) since my original post, and it's looking like they'll miss the October milestone as well), I'd love to see a fix for this issue in the interim.

**Comment by guardrex** [comment] 2016-10-21 05:07
I never was able to get back to this. I'm working 60-hour weeks on professional projects these days with no end in sight at the moment.

**Comment by guardrex** [comment] 2017-02-09 01:33
Just released v0.2.0 that fixes this issue.

You can add and use a `command` property on individual tasks. If you do so, the global `command` and `args` are not applied.

If you leave your command and arguments in the `args` property and don't specify a task `command`, then the global `command` and `args` will be used.

```json
{
    "version": "0.1.0",
    "command": "cmd",
    "isShellCommand": true,
    "showOutput": "silent",
    "args": [
        "/c"
    ],
    "test": "blah blah blah",
    "tasks": [
        {
            "taskName": "restore that draws in the global command and args",
            "suppressTaskName": true,
            "args" : ["dotnet", "restore"],
            "showOutput": "always",
            "problemMatcher": "$msCompile"
        },
        {
            "taskName": "restore that doesn't draw in the global command and args",
            "suppressTaskName": true,
            "command": "dotnet",
            "args" : ["restore"],
            "showOutput": "always",
            "problemMatcher": "$msCompile"
        },
```
The first restore command will run ...
```
cmd /c dotnet restore
```
The second restore command will run ...
```
dotnet restore
```

**Closed as completed by guardrex** 2017-02-09 01:33 UTC
Labels: enhancement

**Comment by blackwind** [comment] 2017-02-09 01:38
Seems to work as advertised, with one small caveat: `"options": {"cwd": "${workspaceRoot}/.."}` isn't respected.

**Comment by guardrex** [comment] 2017-02-09 01:40
Correct ... that's not a feature. I'll open an issue. That one isn't so bad ... the upcoming feature that they are planning for chaining tasks together will be a pain.
